config/routes.rb
Community::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :messages

  devise_for :users

  resources :articles do
    resources :comments
  end

  resources :users do
    member do
      post 'follow'
      post 'unfollow'
    end

    resources :articles, :only => [:index]
    resource :profile, :only => [:show]
  end

  resource :profile, :only => [:show, :edit, :update]

  match '/about' => 'pages#about'
  match '/profile/:id/avatar' => 'profiles#avatar', :as => :avatar

  root :to => 'articles#index'


end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, :class_name => 'User'
  belongs_to :recipient, :class_name => 'User'
  validates_presence_of :recipient_id, :message => 'Wrong recipient'
  validates_presence_of :sender_id
  validates_presence_of :message
  attr_accessible :title, :message, :recipient_username

  scope :by_newest, -> { order('created_at DESC') }

  delegate :username, to: :sender, prefix: true
  delegate :username, to: :recipient, prefix: true, allow_nil: true

  def recipient_username=(value)
    user = User.find_by_username(value)
    self.recipient_id = user.id if user
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  def index
    @messages = @messages.by_newest.page(params[:page])
  end

  def new
  end

  def create
    if @message.save
      flash[:notice] = 'The message has been sent'
      redirect_to messages_path
    else
      flash[:alert] = 'The message has not been sent'
      render action: 'new'
    end
  end

  def show
  end

  def destroy
    @message.destroy
    redirect_to messages_path
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<div id="message_form">
<%= form_for @message do |f| %>
  <%= f.error_messages %>
  <dl>
    <dt><%= f.label :recipient_username, "To" %></dt>
    <dd><%= f.text_field :recipient_username %></dd>
    <dt><%= f.label :title %></dt>
    <dd><%= f.text_field :title %></dd>
    <dt><%= f.label :message %></dt>
    <dd><%= f.text_area :message %></dd>
  </dl>
  <%= f.submit "Send" %>
<% end %>
</div>

app/views/messages/index.html.erb
<%= link_to 'New message', new_message_path, :id => 'new_message_link' %>
<% if @messages.count > 0 %>
  <h3 class="centered">Incoming messages</h3>
  <table id="messages_table">
    <colgroup>
      <col id="title_column" />
      <col id="from_column" />
      <col id="posted_column" />
      <col id="edit_column" />
      <col id="delete_column" />
    </colgroup>
    <tr>
      <th>Title</th>
      <th>From</th>
      <th>Posted</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
    </tr>
  <% @messages.each do |message| %>
    <tr>
      <td><%= message.title ||= '<no title>' %></td>
      <td><%= link_to message.sender_username, user_profile_path(message.sender) %></td>
      <td><%= time_ago_in_words(message.created_at) %> ago</td>
      <td><%= button_to 'View', message_path(message), :method => :get %></td>
      <td><%= button_to 'Delete', message_path(message), :method => :delete %></td>
    </tr>
  <% end %>
  </table>
<%= paginate @messages %>
<% else %>
  <div id="no_messages_notice">Your incoming messages list is empty</div>
<% end %>

app/views/messages/new.html.erb
<span class="breadcrumb"><%= link_to 'Messages >> ', messages_path %>New message</span>
<%= render 'form' %>

app/views/messages/show.html.erb
<span class="breadcrumb"><%= link_to 'Messages >> ', messages_path %>Message</span>
<p>Title: <%= @message.title ||= '<no title>' %></p>
<p>Sent by: <%= link_to @message.sender_username, user_profile_path(@message.sender) %>
 <%= time_ago_in_words(@message.created_at) %> ago</p>
<p><%= @message.message%></p>