config/routes.rb
Community::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :messages

  devise_for :users

  resources :articles do
    resources :comments
  end

  resources :users do
    member do
      post 'follow'
      post 'unfollow'
    end

    resources :articles, :only => [:index]
    resource :profile, :only => [:show]
  end

  resource :profile, :only => [:show, :edit, :update]

  match '/about' => 'pages#about'
  match '/profile/:id/avatar' => 'profiles#avatar', :as => :avatar

  root :to => 'articles#index'


end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  acts_as_taggable_on :interests

  has_attached_file :avatar,
    :default_url => '/images/noavatar_:style.jpeg',
    :url => '/profile/:id/avatar?style=:style',
    :storage => :database,
    :styles => {
      :original => {:geometry => "300x300>", :column => 'avatar_file'},
      :medium => {:geometry => "120x120>", :column => 'avatar_medium_file'},
      :thumb =>  {:geometry => "32x32>", :column => 'avatar_thumb_file'}
    }

  validates_presence_of :name
  validates_length_of :name, :maximum => 50
  validates_inclusion_of :gender, :in => ['male', 'female']
  validates_inclusion_of :birthday, :in => Date.new(1900, 1, 1)..(Date.today - 16.years)


  def get_avatar_file(style)
    return avatar_thumb_file if style == 'thumb'
    return avatar_medium_file if style == 'medium'
    return avatar_file if style == 'original'
  end

  def avatar_url(*args)
    avatar.url(*args)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :avatar]
  before_filter :find_user, only: [:show]
  before_filter :find_profile, only: [:show]
  before_filter :find_current_user_profile, only: [:edit, :update]
  helper_method :favorite_bloggers

  def show
  end

  def edit
  end

  def update
    if @profile.update_attributes params[:profile]
      flash[:notice] = 'The profile has been updated'
      redirect_to profile_path
    else
      flash[:alert] = 'The profile has not been updated'
      render :action => 'edit'
    end
  end

  def avatar
    @profile = Profile.find(params[:id])
    @avatar = @profile.get_avatar_file params[:style]
    send_data(@avatar, :type => @profile.avatar_content_type, :disposition => 'inline')
  end

  private

  def find_user
    @user = User.find(params[:user_id]) if params[:user_id]
    @user ||= current_user
    redirect_to new_user_session_path unless @user
  end

  def find_profile
    @profile = @user.profile
  end

  def find_current_user_profile
    @profile = current_user.profile
  end

  def favorite_bloggers
    @favorite_bloggers ||= @user.bloggers.page params[:page]
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for @profile, :html => { :multipart => true } do |f| %>
  <%= f.error_messages %>
  <dl>
    <dt><%= f.label :avatar %></dt>
    <dd><%= f.file_field :avatar %></dd>

    <dt><%= f.label :name %></dt>
    <dd><%= f.text_field :name %></dd>

    <dt>Gender</dt>
    <dd>
        <%= f.radio_button :gender, 'male' %>
        <%= f.label :gender_male, 'male' %>
        <%= f.radio_button :gender, 'female' %>
        <%= f.label :gender_female, 'female' %>
    </dd>

    <dt><%= f.label :birthday, 'Birthday' %></dt>
    <dd>
      <%= f.date_select :birthday,
                      :start_year => Time.now.year - 16,
                      :end_year => 1930,
                      :order => [:day, :month, :year] %>
    </dd>

    <dt><%= f.label :info, 'About me' %></dt>
    <dd><%= f.text_area :info %></dd>

    <dt><%= f.label :interest_list, 'Interests' %></dt>
    <dd>
      <%= f.text_field :interest_list %>
      <span>(separate tags with comma symbol)</span>
    </dd>
  </dl>
  <%= f.submit %>
<% end %>

app/views/profiles/edit.html.erb
<h3>Edit profile</h3>
<%= render 'form' %>

app/views/profiles/show.html.erb
<div id="show_profile">
  <h3><%= @user.username %>'s profile</h3>

  <div id="personal_information">
    <%= image_tag @profile.avatar_url(:original), :id => 'original_avatar' %>
    <dl>
      <dt>Name</dt>
      <dd><%= @profile.name %></dd>
      <dt>Gender</dt>
      <dd><%= @profile.gender %></dd>
      <dt>Birthday</dt>
      <dd><%= @profile.birthday.strftime("%d %B %Y") %></dd>
      <dt>About me</dt>
      <dd><%= @profile.info %></dd>
      <dt>Interests</dt>
      <dd><%= @profile.interest_list %></dd>
    </dl>
    <div class="clear"></div>
      <% if user_signed_in? && current_user == @user %>
        <%= link_to 'Edit', edit_profile_path, :id => 'edit_profile_link' %>
      <% else %>
        <%= link_to 'Read blog', user_articles_path(@user), :id => 'read_blog_link' %>
      <% end %>
  </div>


  <div id="following">
   <h4>Favorite bloggers</h4>
    <% favorite_bloggers.each do |blogger| %>
      <div class="favorite_blogger">
        <%= link_to image_tag(blogger.profile_avatar_url(:thumb)), user_profile_path(blogger), :class => 'avatar' %>
        <%= link_to "#{blogger.username} (#{blogger.profile_name})", user_profile_path(blogger), :class => 'name' %>
        <div class="clear"></div>
      </div>
    <% end %>
    <%= paginate favorite_bloggers %>
  </div>

  <div class="clear"></div>
</div>