config/routes.rb
Community::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :messages

  devise_for :users

  resources :articles do
    resources :comments
  end

  resources :users do
    member do
      post 'follow'
      post 'unfollow'
    end

    resources :articles, :only => [:index]
    resource :profile, :only => [:show]
  end

  resource :profile, :only => [:show, :edit, :update]

  match '/about' => 'pages#about'
  match '/profile/:id/avatar' => 'profiles#avatar', :as => :avatar

  root :to => 'articles#index'


end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :title, :content, :presence => true
  attr_accessible :title, :content
  acts_as_taggable
  acts_as_indexed :fields => [:title, :content]
  acts_as_commentable


  scope :default_list, -> { with_users_and_profiles.with_tags.by_newest }
  scope :in_blogs_selected_by, ->(user) { where("user_id IN
   (SELECT blogger_id FROM blogger_readers WHERE reader_id =#{user.id})") }
  scope :by_newest, order('created_at DESC')
  scope :with_tags, includes(:tags)
  scope :with_users_and_profiles, includes(:user => :profile)

  delegate :username, :profile_name, to: :user, prefix: true

  def threaded_comments
    self.comment_threads.order('lft')
  end

end

app/controllers/articles_controller.rb
require 'cgi'
class ArticlesController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  before_filter :find_user, :only => [:show, :index]
  before_filter :find_article, :only => [:show, :edit, :update, :destroy]

  authorize_resource :except => [:index, :show]



  def index
    @articles = articles.default_list.page(params[:page])
    @articles = @articles.tagged_with(unescaped_tag) if params[:tag]
    @articles = @articles.tagged_with(params[:query]) if params[:query] && params[:mode] == 'tags'
    @articles = @articles.with_query(params[:query]) if params[:query] && params[:mode] == 'content'
    @articles = @articles.in_blogs_selected_by(current_user) if params[:selected_blogs] && current_user
    @tag_counts = Article.tag_counts
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.build params[:article]
    @article.tag_list = params[:tags]

    if @article.save
      flash[:notice] = 'The article has been created'
      redirect_to article_path(@article)
    else
      flash[:alert] = 'The article has not been created'
      render :action => 'new'
    end
  end

  def show
    @user = @article.user
    @comments = @article.threaded_comments.page(params[:page])
  end

  def edit
  end

  def update
    @article.tag_list = params[:tags] if params[:tags]

    if @article.update_attributes(params[:article])
      flash[:notice] = 'The article has been updated'
      redirect_to article_path(@article)
    else
      flash[:alert] = 'The article has not been updated'
      render :action => 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:notice] = 'The article has been deleted'
    redirect_to user_articles_path(current_user)
  end


  private

  def find_article
    @article = Article.find(params[:id])
  end

  def find_user
    @user = User.find_by_id(params[:user_id])
  end

  def articles
    @user ? @user.articles : Article.scoped
  end

  def unescaped_tag
    CGI.unescape params[:tag]
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  include ActsAsTaggableOn::TagsHelper

  def print_tags(article)
    if !params[:tags] && article.tag_list
      article.tag_list.join(", ") 
    else
      params[:tags]
    end
  end

 
  
end

app/views/articles/_articles.html.erb
<div id='articles'>
  <ul>
    <% @articles.each do |article| %>
      <li>
        <h4><%= link_to article.title, article_path(article) %></h4>
        <p><%= snippet(article.content, 100, '...').html_safe %></p>
        <ul id="tag_list">
          <% article.tags.each do |item| %>
            <li>
              <%= link_to item, articles_path(:tag => CGI::escape(item.name)) %>
            </li>
          <% end %>
        </ul>
        <div class="article_info">

          <%= link_to image_tag(article.user.profile.avatar.url(:thumb)),
             user_profile_path(article.user), :class => 'avatar' %>
          <%= link_to "#{article.user_username} (#{article.user_profile_name})",
            user_profile_path(article.user), :class => 'name' %>
          <span class="publicated"><%= time_ago_in_words(article.created_at) %> ago</span>
          <div class="clear">&nbsp;</div>
        </div>

      </li>
    <% end %>
 </ul>
<%= paginate @articles %>
</div>

app/views/articles/_blog_owner.html.erb
<span id="blog_owner"><%= @user.username %>'s blog</span>
<%= link_to image_tag(@user.profile_avatar_url(:medium)),
             user_profile_path(@user), :id => 'blogger_avatar' %>
<% if user_signed_in? && current_user == @user %>
  <%= link_to 'Add post', new_article_path, :id => 'add_post_link' %>
<% end %>

  <% if user_signed_in? && current_user != @user %>
    <div id="follow_unfollow_button">
      <% if current_user.bloggers.include? @user %>
        <%= button_to 'Unfollow', unfollow_user_path(@user) %>
      <% else %>
        <%= button_to 'Follow', follow_user_path(@user) %>
      <% end %>
    </div>
  <% end %>

app/views/articles/_form.html.erb
<%= javascript_include_tag "/javascripts/ckeditor/ckeditor.js" %>
<%= form_for @article do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p> 
  <p>
    <%= f.label :content %>
    <%= f.cktext_area :content,:label => false, :input_html => { :toolbar => 'Basic' } %>
  </p> 
  <p>
    <%= label_tag :tags %>
    <%= text_field_tag :tags, print_tags(@article) %>
    <span>(separate tags with comma symbol)</span>
  </p>
  <%= f.submit %>
<% end %>

app/views/articles/_search_form.html.erb
<div id="blog_search_form">
    <%= form_tag articles_path, :method => :get, :remote => true do %>
      <%= radio_button_tag :mode, 'content', params[:mode] != 'tags' %>
      <%= label_tag :mode_content, 'by content'  %>
      <%= radio_button_tag :mode, 'tags', params[:mode] == 'tags' %>
      <%= label_tag :mode_tags, 'by tags (separate with comma)' %>
      <%= text_field_tag :query, params[:query] %>
      <%= submit_tag 'Search' %>
      <% if user_signed_in? %>
        <div id="in_selected_blogs">
          <%= check_box_tag :selected_blogs, 'on', params[:selected_blogs] == 'on' %>
          <%= label_tag :selected_blogs, 'in selected blogs' %>
        </div>
      <% end %>
    <% end %>
</div>

<div id="tag_cloud">
  <% tag_cloud(@tag_counts, %w(css1 css2 css3 css4)) do |tag, css_class| %>
    <span>
      <%= link_to tag.name, { :tag => tag.name }, :class => css_class %>
    </span>
  <% end %>
</div>

app/views/articles/edit.html.erb
<span class="breadcrumb"><%= link_to 'My blog >> ', user_articles_path(current_user)%>Edit article</span>
<%= render 'form'%>

app/views/articles/index.html.erb
<%= render 'blog_owner' if @user %>
<%= render 'search_form' unless @user %>
<%= render 'articles' %>

app/views/articles/index.js.erb
$('#articles').html('<%= j render 'articles' %>');

app/views/articles/new.html.erb
<span class="breadcrumb"><%= link_to 'My blog >> ', user_articles_path(current_user)%> New article</span>
<%= render 'form'%>

app/views/articles/search.html.erb
<div id="blog_search_form">
    <%= form_tag search_articles_path, :remote => true do %>
      <%= radio_button_tag :mode, 'content', params[:mode] != 'tags' %>
      <%= label_tag :mode_content, 'by content'  %>
      <%= radio_button_tag :mode, 'tags', params[:mode] == 'tags' %>
      <%= label_tag :mode_tags, 'by tags (separate with comma)' %>
      <%= text_field_tag :query, params[:query] %>
      <%= submit_tag 'Search' %>
      <% if user_signed_in? %>
        <div id="in_selected_blogs">
          <%= check_box_tag :selected_blogs, 'on', params[:selected_blogs] == 'on' %>
          <%= label_tag :selected_blogs, 'in selected blogs' %>
        </div>
      <% end %>
    <% end %>
</div>

<div id="tag_cloud">
  <% tag_cloud(@tag_counts, %w(css1 css2 css3 css4)) do |tag, css_class| %>
    <span>
      <%= link_to tag.name, { :action => :search_by_tag, :tag => tag.name }, :class => css_class %>
    </span>
  <% end %>
</div>

<%= render 'articles' %>

app/views/articles/search.js.erb
$('#articles').html('<%= j render 'articles' %>');

app/views/articles/show.html.erb
<div class="full_article">
  <%= link_to "#{@user.username}'s blog", user_articles_path(@user),
      :id => 'link_to_blog_index'%>
  <div class="clear"></div>

  <h3><%= @article.title %></h3>
  <p><%= @article.content.html_safe %></p>
    <ul id="tag_list">
        <% @article.tags.each do |item| %>
          <li><%= link_to item, articles_path(:tag => CGI::escape(item.name)) %></li>
        <% end %>
    </ul>

  <div class="article_info">
    <%= link_to image_tag(@user.profile.avatar.url(:thumb)),
       user_profile_path(@user), :class => 'avatar' %>

    <%= link_to "#{@user.username} (#{@user.profile_name})",
      user_profile_path(@user), :class => 'name' %>

    <span class="publicated"><%= time_ago_in_words(@article.created_at) %> ago</span>

    <% if user_signed_in? && current_user == @article.user %>
      <%= link_to image_tag('/images/delete.png', :alt => 'Delete', :title => 'Delete'),
        article_path(@article), :id => 'article_delete_link',
        :method => :delete, :confirm => 'Are you sure you want to delete this article?' %>

      <%= link_to image_tag('/images/edit.gif', :alt => 'Edit', :title => 'Edit'),
        edit_article_path(@article), :id => 'article_edit_link' %>
    <% end %>
    <div class="clear"></div>
  </div>

<h3>Comments</h3>
  <% if user_signed_in? %>
    <%= link_to 'Add comment', new_article_comment_path(@article) %>
  <% end %>

  <div class="comments">
    <%= render @comments, commented: @article %>
    <%= paginate @comments %>
  </div>
</div>